steps:
  # Install dependencies
  - name: 'node:20'
    entrypoint: npm
    args: ['install']
    dir: 'projects/ssg-app'

  # Build the SSG app
  - name: 'node:20'
    entrypoint: npm
    args: ['run', 'build']
    dir: 'projects/ssg-app'
    env:
      - 'NODE_ENV=production'

  # Optional: Run tests
  - name: 'node:20'
    entrypoint: npm
    args: ['test', '--if-present']
    dir: 'projects/ssg-app'

  # Build the server-side rendering (SSR) bundle
  - name: 'node:20'
    entrypoint: npm
    args: ['run', 'build:ssr']
    dir: 'projects/ssg-app'

# Artifacts configuration - adjust the paths based on your build output
artifacts:
  objects:
    location: 'gs://${_BUCKET_NAME}/ssg-app/'
    paths: ['projects/ssg-app/dist/**']

# You can specify a timeout if needed
timeout: '1800s'

# Substitutions
substitutions:
  _BUCKET_NAME: your-storage-bucket # Replace with your actual storage bucket name